# Generated by Django 5.0.6 on 2024-07-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReduceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("electricity", models.FloatField()),
                ("gas", models.FloatField()),
                ("water", models.FloatField()),
                ("electricity_cost", models.FloatField(default=0.0)),
                ("gas_cost", models.FloatField(default=0.0)),
                ("water_cost", models.FloatField(default=0.0)),
            ],
        ),
    ]
