# Generated by Django 5.0.6 on 2024-06-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reduceReports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reducereport",
            name="company_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="reducereport",
            name="electricity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="reducereport",
            name="gas",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="reducereport",
            name="water",
            field=models.FloatField(),
        ),
    ]
