# Generated by Django 5.0.6 on 2024-06-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reduceReports", "0002_alter_reducereport_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reducereport",
            name="company_name",
            field=models.CharField(max_length=100),
        ),
    ]
