# Generated by Django 5.0.6 on 2024-06-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reduceReports", "0003_alter_reducereport_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="reducereport",
            name="electricity_cost",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="reducereport",
            name="gas_cost",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="reducereport",
            name="water_cost",
            field=models.FloatField(default=0.0),
        ),
    ]
